{
 "title": "QOS RTCP",
 "tags": [ "qos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Jitter > 10 ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_jitter[30m]) > 10 and changes(heplify_rtcp_jitter[1m]) > 0",
     "legendFormat": "rtcp_jitter"
    }
   ]
  },
  {
   "title": "RTT > 4 ms",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcpxr_round_trip_delay[30m]) > 4 and changes(heplify_rtcpxr_round_trip_delay[1m]) > 0",
     "legendFormat": "rtcpxr_round_trip_delay"
    }
   ]
  },
  {
   "title": "Packet Loss > 10",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_packets_lost[30m]) > 10 and changes(heplify_rtcp_packets_lost[1m]) > 0",
     "legendFormat": "rtcp_packets_lost"
    }
   ]
  },
  {
   "title": "Fraction Loss > 10",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_fraction_lost[30m]) > 10 and changes(heplify_rtcp_fraction_lost[1m]) > 0",
     "legendFormat": "rtcp_fraction_lost"
    },
    {
     "expr": "avg_over_time(heplify_rtcpxr_fraction_lost[30m]) > 10 and changes(heplify_rtcpxr_fraction_lost[1m]) > 0",
     "legendFormat": "rtcpxr_fraction_lost"
    }
   ]
  }
 ]
}