{
 "title": "SIP KPIs",
 "tags": [ "sip" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tn",
    "label": "interface_name",
    "query": "label_values(heplify_method_response, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "SER (ASR)",
   "type": "timeseries",
   "description": "SIP\n\nSER = Session Establishment Ratio\n\n``` \n           # of INVITE Requests \n            w/ associated 200 OK\nSER = ----------------------------------- x 100\n         (Total # of INVITE Requests) -\n   \t(# of INVITE Requests w/ 3XX Response)\n```\nsimilar to\n\nE.411\n\nASR = Answer Seizure Ratio\n\nGenerally measured at originating UA only.\n\nhttps://tools.ietf.org/html/rfc6076#section-4.6",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[30m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[30m])) or sum(up) * 0)), 100)",
     "legendFormat": "SER (ASR) current"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[30m] offset 1w)) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m] offset 1w)) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[30m] offset 1w)) or sum(up) * 0)), 100)",
     "legendFormat": "SER (ASR) last week"
    }
   ]
  },
  {
   "title": "SEER (NER)",
   "type": "timeseries",
   "description": "SIP\n\nSEER = Session Establishment Effectiveness Ratio\n\n```\n# of INVITE Requests w/ associated \n 200, 480, 486, 600, or 603\n--------------------------------- x 100\n(Total # of INVITE Requests) -\n  (# of INVITE Requests w/ 3XX Response)\n```\nsimilar to E.411\n\nNER = Network Effectiveness Ratio\n\nhttps://tools.ietf.org/html/rfc6076#section-4.7",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"200|480|486|600|603\"}[30m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[30m])) or sum(up) * 0)), 100)",
     "legendFormat": "SEER (NER) current"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"200|480|486|600|603\"}[30m] offset 1w)) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m] offset 1w)) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[30m] offset 1w)) or sum(up) * 0)), 100)",
     "legendFormat": "SEER (NER) last week"
    }
   ]
  },
  {
   "title": "SCR",
   "type": "timeseries",
   "description": "SIP\n\nSCR = Session Completion Ratio\n\n```\n       # of Successfully Completed Sessions\nSCR % = ----------------------------------- x 100\n            Total # of Session Requests\n```\nsimilar to E.411\n\nCCR = Call Completion Ratio\n\nhttps://tools.ietf.org/html/rfc6076#section-4.9",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"BYE\", response=\"200\"}[30m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m]))), 100)",
     "legendFormat": "SCR current"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"BYE\", response=\"200\"}[30m] offset 1w)) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m] offset 1w))), 100)",
     "legendFormat": "SCR last week"
    }
   ]
  },
  {
   "title": "IRA & ISA",
   "type": "timeseries",
   "description": "SIP\n\nIRA = Ineffective Registration Attempts\n```\n\n                  # of IRAs\nIRA % = ----------------------------- x 100\n         Total # of REGISTER Requests\n```\nhttps://tools.ietf.org/html/rfc6076#section-4.2\n\nISA = Ineffective Session Attempts\n```\n                # of ISAs\nISA % = ----------------------------- x 100\n       Total # of Session Requests\n```\nhttps://tools.ietf.org/html/rfc6076#section-4.8\n",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"4.*|5.*|6.*\"}[30m])) - \nsum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=~\"401|402|407\"}[30m]))) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"REGISTER\"}[30m]))), 100)",
     "legendFormat": "IRA"
    },
    {
     "expr": "clamp_max((sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"408|500|503|504\"}[30m])) * 100) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[30m]))), 100)",
     "legendFormat": "ISA"
    }
   ]
  }
 ]
}